apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-console
  labels:
    app: redpanda-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda-console
  template:
    metadata:
      labels:
        app: redpanda-console
    spec:
      containers:
        - name: redpanda-console
          image: redpandadata/console:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKERS
              value: "redpanda.default.svc.cluster.local:9092"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
