apiVersion: v1
kind: Service
metadata:
  name: redpanda-console
  labels:
    app: redpanda-console
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: redpanda-console
