{{- if .Values.g2krepeater.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: g2krepeater
  labels:
    app: g2krepeater
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
  selector:
    app: g2krepeater
{{- end }}

