{{- if .Values.redpandaConsole.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-console
  labels:
    app: redpanda-console
spec:
  replicas: {{ .Values.redpandaConsole.replicas }}
  selector:
    matchLabels:
      app: redpanda-console
  template:
    metadata:
      labels:
        app: redpanda-console
    spec:
      containers:
        - name: redpanda-console
          image: {{ .Values.redpandaConsole.image | quote }}
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKERS
              value: {{ .Values.redpandaConsole.kafkaBrokers | quote }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: redpanda-console
  labels:
    app: redpanda-console
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: redpanda-console
{{- end }}

