{{- if .Values.redpanda.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
  labels:
    app: redpanda
spec:
  replicas: {{ .Values.redpanda.replicas }}
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
        - name: redpanda
          image: {{ .Values.redpanda.image | quote }}
          args:
            - redpanda
            - start
            {{- if .Values.redpanda.overprovisioned }}
            - --overprovisioned
            {{- end }}
            - --smp
            - "{{ .Values.redpanda.smp }}"
            - --memory
            - "{{ .Values.redpanda.memory }}"
            - --reserve-memory
            - "{{ .Values.redpanda.reserveMemory }}"
            - --node-id
            - "{{ .Values.redpanda.nodeId }}"
            - --check=false
            - --kafka-addr
            - "PLAINTEXT://0.0.0.0:{{ .Values.redpanda.containerPort }}"
            - --advertise-kafka-addr
            - "PLAINTEXT://{{ .Values.redpanda.kafkaAdvertisedHost }}:{{ .Values.redpanda.containerPort }}"
          ports:
            - containerPort: {{ .Values.redpanda.containerPort }}
          resources:
            limits:
              memory: {{ .Values.redpanda.resources.limits.memory | quote }}
{{- end }}

---
{{- if .Values.redpanda.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redpanda
  labels:
    app: redpanda
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redpanda.containerPort }}
      name: kafka
  selector:
    app: redpanda
{{- end }}

